baseURL = 'https://blog.benmagill.co.uk/'
languageCode = 'en-gb'
title = 'Ben Magill'
theme = 'PaperMod'

#sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 2
  [[menus.main]]
    name = "Books"
    pageRef = "/books"
    weight = 3
[params]
	social = true
