baseURL = 'https://blog.benmagill.co.uk/'
languageCode = 'en-gb'
title = 'Ben Magill'
theme = 'PaperMod'

#sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 2
  [[menus.main]]
    name = "Books"
    pageRef = "/books"
    weight = 3
[params]
	social = true
  keywords = ["Blog", "Portfolio"]
  author = "Me"
  ShowWordCount= true
  [params.homeInfoParams]
    title = "Welcome!"
    content = "Below you can find my most recent blog posts. You can also find my [resume](/resume), [portfolio](/portfolio) and [recommended books](/books)."
